### ISSUE TITLE
Overriding default register route

### ISSUE THREAD

**Issue by DylanBaine** [PT-83/famijam#3]
https://github.com/PT-83/famijam/blob/772259d7ace14fa7e48c38ac12d6143b93f42f63/routes/web.php#L34
The line above isn't needed because the `Auth::routes();` method mentioned below takes care of this for us. Get rid of line 34 line, and users will be redirected to the home route as you intend.

https://github.com/PT-83/famijam/blob/772259d7ace14fa7e48c38ac12d6143b93f42f63/routes/web.php#L24

**Comment by PT-83** [comment]
Hey, I removed the line but then get a 500 server?
